image: maven:3.6.1-jdk-11

stages:
  - build
  - style
  - docs

build:
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar

style:
  stage: style
  script:
    - mvn formatter:validate

docs:
  stage: docs
  script:
    - mvn javadoc:javadoc
  only:
    - merge_request
  artifacts:
    paths:
      - target/site
